### ISSUE TITLE
Inconsistent Patterns for AE2 recipes

### ISSUE THREAD

**Issue by Krutoy242** [friendlyhj/AdvancedTweakery#1]
When pressing `[+]` button in Terminals from AE2, recipe output inherit `display` tags. This result in recipes can't be finished by AE2 autocrafting unless output would be rewritten manually (by ghost dragging items instead of pressing `[+]` button).

Please remove `display` tags or at least remove them for recipes where output is always 100%.

![image](https://github.com/friendlyhj/AdvancedTweakery/assets/936618/1f0c59ab-77ae-4104-b03c-a22ade71c1e4)

**Comment by friendlyhj** [comment]
Add IItemStack argument for `ourputs` method to solve the problem.
