### ISSUE TITLE
The crash report

### ISSUE THREAD

**Issue by Raaadial** [friendlyhj/AdvancedTweakery#3]
[crash-2024-05-15_14.24.18-client.txt](https://github.com/friendlyhj/AdvancedTweakery/files/15317307/crash-2024-05-15_14.24.18-client.txt)
[crash-2024-05-15_14.26.51-client.txt](https://github.com/friendlyhj/AdvancedTweakery/files/15317308/crash-2024-05-15_14.26.51-client.txt)

**Comment by friendlyhj** [comment]
脚本也发下啊，最起码 issue 要是个完整的反馈啊，最好用 mclo.gs 传

**Comment by Raaadial** [comment]
https://mclo.gs/GuNa54K （脚本）

**Comment by friendlyhj** [comment]
若物品输出为空，则不能设置 `maxOutputSize`。
